# -*- coding: utf-8 -*-
"""Face Helmet Detection using YOLO V8 / YOLO V5 / faster RCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMyyCZ5OH2fqtW-ZoqQ0mdyhylU_zZk-
"""

!pip install ultralytics -q
!pip install Pillow matplotlib seaborn -q

import os, shutil, random, xml.etree.ElementTree as ET
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import matplotlib.pyplot as plt
from pathlib import Path
import matplotlib.image as mpimg
from ultralytics import YOLO
import pandas as pd

import os
import kagglehub
from google.colab import userdata

# 1. Connect your Colab secrets to the environment
os.environ["KAGGLE_USERNAME"] = userdata.get('KAGGLE_USERNAME')
os.environ["KAGGLE_KEY"] = userdata.get('KAGGLE_KEY')

# 2. Download the specific helmet-detection dataset
print("Downloading dataset... please wait.")
path = kagglehub.dataset_download("andrewmvd/helmet-detection")

print(f"\n✅ Success! Dataset downloaded to: {path}")

# 3. See what's inside
print("\nFiles in your dataset folder:")
for root, dirs, files in os.walk(path):
    level = root.replace(path, '').count(os.sep)
    indent = ' ' * 4 * (level)
    print(f"{indent}{os.path.basename(root)}/")
    subindent = ' ' * 4 * (level + 1)
    for f in files[:764]:
        print(f"{subindent}{f}")

dataset_path = Path(path)


image_files = sorted(list(dataset_path.glob("**/images/*.png")))
xml_files = sorted(list(dataset_path.glob("**/annotations/*.xml")))

if len(image_files) == 0:
    image_files = sorted(list(dataset_path.rglob("*.png")))
    xml_files = sorted(list(dataset_path.rglob("*.xml")))

xml_map = {x.stem: x for x in xml_files}

print(f"Total Images found: {len(image_files)}")
print(f"Total XMLs found: {len(xml_map)}")

print(path)

import shutil
from pathlib import Path

# In Colab, we use /content/ instead of /kaggle/working/
WORK_DIR = Path("/content/helmet_project")

if WORK_DIR.exists():
    shutil.rmtree(WORK_DIR)

for split in ["train", "val", "test"]:

    # Detection folders (YOLO format)
    (WORK_DIR / "detection" / split / "images").mkdir(parents=True, exist_ok=True)
    (WORK_DIR / "detection" / split / "labels").mkdir(parents=True, exist_ok=True)

    # Classification folders (Standard CNN format)
    (WORK_DIR / "classification" / split / "With_Helmet").mkdir(parents=True, exist_ok=True)
    (WORK_DIR / "classification" / split / "Without_Helmet").mkdir(parents=True, exist_ok=True)

CLASS_MAP = {
    "with helmet": 0,
    "without helmet": 1
}

print(f"Directory structure created at: {WORK_DIR}")

def xml_to_yolo(xml_path, img_w, img_h):
    tree = ET.parse(xml_path)
    root = tree.getroot()

    yolo_lines = []

    for obj in root.findall("object"):
        name = obj.find("name").text.lower().strip()

        # Make sure the class is in our map
        if name not in CLASS_MAP:
            continue

        cls_id = CLASS_MAP[name]

        # Extract bounding box coordinates
        bb = obj.find("bndbox")
        xmin = float(bb.find("xmin").text)
        ymin = float(bb.find("ymin").text)
        xmax = float(bb.find("xmax").text)
        ymax = float(bb.find("ymax").text)

        # YOLO format: <object-class> <x_center> <y_center> <width> <height>
        # All values are normalized (0.0 to 1.0)
        cx = ((xmin + xmax) / 2) / img_w
        cy = ((ymin + ymax) / 2) / img_h
        w  = (xmax - xmin) / img_w
        h  = (ymax - ymin) / img_h

        line = f"{cls_id} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}"
        yolo_lines.append(line)

    return yolo_lines

import random

# Shuffle images for a random split
random.seed(42)
random.shuffle(image_files)

# Define split ratios (80% train, 10% val, 10% test)
train_split = int(0.8 * len(image_files))
val_split = int(0.9 * len(image_files))

splits = {
    "train": image_files[:train_split],
    "val": image_files[train_split:val_split],
    "test": image_files[val_split:]
}

for split_name, files in splits.items():
    for img_path in files:
        # 1. Open image to get dimensions
        img = Image.open(img_path)
        w, h = img.size

        # 2. Convert XML to YOLO format
        xml_path = xml_map.get(img_path.stem)
        if xml_path:
            yolo_labels = xml_to_yolo(xml_path, w, h)

            # 3. Save Image to detection folder
            shutil.copy(img_path, WORK_DIR / "detection" / split_name / "images" / img_path.name)

            # 4. Save Label (.txt) to detection folder
            label_name = img_path.stem + ".txt"
            with open(WORK_DIR / "detection" / split_name / "labels" / label_name, "w") as f:
                f.write("\n".join(yolo_labels))

print("✅ Data conversion and splitting complete!")

yaml_content = f"""
path: {WORK_DIR}/detection  # dataset root dir
train: train/images
val: val/images
test: test/images

# Classes
names:
  0: with helmet
  1: without helmet
"""

with open(WORK_DIR / "data.yaml", "w") as f:
    f.write(yaml_content)

print("✅ data.yaml created!")

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Train the model
# 'data' points to your yaml file
# 'epochs' is how many times the model sees the data (start with 25-50)
# 'imgsz' is the image size (usually 640)
results = model.train(
    data=str(WORK_DIR / "data.yaml"),
    epochs=50,
    imgsz=640,
    plots=True
)

# Search for the image in the whole project directory
search_results = list(WORK_DIR.rglob("BikesHelmets715.png"))

if search_results:
    actual_path = str(search_results[0])
    print(f"✅ Found it! The correct path is: {actual_path}")

    # Run prediction using the path we just found
    model.predict(source=actual_path, save=True, conf=0.5, name='specific_test', exist_ok=True)
else:
    print("❌ That image name doesn't exist anywhere in the project folder.")

import os
from pathlib import Path
from PIL import Image

# 1. Search for the image anywhere in your project
target_filename = "BikesHelmets239.png"
search_results = list(WORK_DIR.rglob(target_filename))

if not search_results:
    print(f"❌ Could not find {target_filename} anywhere in {WORK_DIR}")
else:
    my_image = str(search_results[0])
    print(f"✅ Found image at: {my_image}")

    # 2. Run Prediction
    results = model.predict(source=my_image, conf=0.5)

    # 3. Analyze Results for this particular image
    for r in results:
        boxes = r.boxes
        if len(boxes) == 0:
            print("No helmets or heads detected in this specific image.")
        else:
            print(f"\n--- Metrics for {target_filename} ---")
            # Calculate Average Confidence for the whole image
            avg_conf = boxes.conf.mean().item()
            print(f"Average Confidence Score: {avg_conf:.2%}")

            # Print individual detection scores
            for i, box in enumerate(boxes):
                label = r.names[int(box.cls[0])]
                score = box.conf[0].item()
                print(f"Object {i+1}: {label} | Score: {score:.2%}")

    # 4. Show the visual result
    res_plotted = results[0].plot()
    display(Image.fromarray(res_plotted[..., ::-1]))

"""3 Models to tell why Yolo V8 is better than:-
  * Yolo V5
  * Faster R-CNN & SSD

"""

# Train YOLOv5 using the same data.yaml
model_v5 = YOLO('yolov5n.pt') # Load YOLOv5 nano version
results_v5 = model_v5.train(
    data=str(WORK_DIR / "data.yaml"),
    epochs=50,
    imgsz=640
)

from IPython.display import Image, display
display(Image(filename='runs/detect/train-3/results.png', width=800))

# This shows you a sample of the actual detections made during validation
display(Image(filename='runs/detect/train-3/val_batch0_pred.jpg', width=900))

print(f"--- YOLOv5 Results ---")
print(f"mAP@50: {results_v5.box.map50:.4f}")
print(f"mAP@50-95: {results_v5.box.map:.4f}")
print(f"Fitness Score: {results_v5.fitness:.4f}")

"""Comparison B/W Yolo V5 & Yolo V8

"""

yolov8_metrics_path = Path('/content/runs/detect/train/results.csv')
yolov8_metrics = pd.read_csv(yolov8_metrics_path)

# Get the last row for final metrics
last_epoch_metrics_v8 = yolov8_metrics.iloc[-1]

# Extract relevant metrics
yolov8_fitness = last_epoch_metrics_v8['metrics/mAP50-95(B)'] # Corrected from 'fitness'
yolov8_map50 = last_epoch_metrics_v8['metrics/mAP50(B)']

data = {
    "Model": ["YOLOv5", "YOLOv8"],
    "Fitness Score": [results_v5.fitness, yolov8_fitness],
    "mAP@50": [results_v5.box.map50, yolov8_map50]
}
df = pd.DataFrame(data)
print(df)

"""Q. why YOLO V8 has Less Fitness Score than YOLOv5?

Ans - YOLO V5uses Anchor Boxes (pre-defined shapes that "guess" where a helmet might be). This gives it a "head start" in the early stages of training because it’s looking for specific boxes.
YOLOv8 is Anchor-Free. It predicts the center of an object directly. While this is more accurate in the long run, it takes more epochs to "learn" how to draw those boxes precisely. If you only trained for 50 epochs, YOLOv8 might just need more time to stabilize.

1. YOLOv8 is designed to capture more "features" (like the strap of the helmet or the reflection on the visor).

2. The Result: Because it's looking for more detail, it can sometimes produce more "False Positives" early on, which brings the fitness score down until the model fine-tunes itself.
"""

import torch
import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torch.utils.data import DataLoader
from torchvision import transforms as T
from PIL import Image # Explicitly import PIL.Image to prevent shadowing issues

torch_class_map = {"background": 0, "with helmet": 1, "without helmet": 2}

class HelmetTorchDataset(torch.utils.data.Dataset):
    def __init__(self, img_dir, annot_dir):
        self.img_dir = img_dir
        self.annot_dir = annot_dir
        self.imgs = sorted([f for f in os.listdir(img_dir) if f.endswith('.png')])

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.imgs[idx])
        xml_path = os.path.join(self.annot_dir, self.imgs[idx].replace('.png', '.xml'))

        img = Image.open(img_path).convert("RGB")
        img_tensor = T.ToTensor()(img)

        tree = ET.parse(xml_path)
        root = tree.getroot()
        boxes, labels = [], []

        for obj in root.findall('object'):
            name = obj.find('name').text.lower().strip()
            labels.append(torch_class_map[name])
            bb = obj.find('bndbox')
            boxes.append([float(bb.find('xmin').text), float(bb.find('ymin').text),
                          float(bb.find('xmax').text), float(bb.find('ymax').text)])

        target = {
            "boxes": torch.as_tensor(boxes, dtype=torch.float32),
            "labels": torch.as_tensor(labels, dtype=torch.int64),
            "image_id": torch.tensor([idx])
        }
        return img_tensor, target

    def __len__(self):
        return len(self.imgs)

test_ds = HelmetTorchDataset(str(path)+"/images", str(path)+"/annotations")
print(f"Dataset ready with {len(test_ds)} images.")

# 1. Load a pre-trained Faster R-CNN model
model_rcnn = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model_rcnn.eval()

# 2. Pick a random image from your dataset
img, target = test_ds[0]
with torch.no_grad():
    prediction = model_rcnn([img])

# 3. Print the detection to the screen
print("Faster R-CNN Detection Output:")
print(f"Found {len(prediction[0]['boxes'])} potential objects.")
print("Boxes:", prediction[0]['boxes'][:3]) # Show first 3 boxes

def show_torch_result(img_tensor, prediction, threshold=0.5):
    img = img_tensor.permute(1, 2, 0).numpy()
    plt.figure(figsize=(10, 6))
    plt.imshow(img)
    ax = plt.gca()

    for box, score in zip(prediction[0]['boxes'], prediction[0]['scores']):
        if score > threshold:
            xmin, ymin, xmax, ymax = box
            rect = patches.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, linewidth=2, edgecolor='r', facecolor='none')
            ax.add_patch(rect)
    plt.title("Faster R-CNN Detection Results")
    plt.show()

# Visualize it!
show_torch_result(img, prediction)

# ============================================================
# FINAL MODEL COMPARISON: YOLOv8 vs YOLOv5 vs Faster R-CNN
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
from pathlib import Path

# -----------------------------------------------------------
# STEP 1: Collect metrics from YOLOv8 (from saved results.csv)
# -----------------------------------------------------------
yolov8_metrics_path = Path('/content/runs/detect/train/results.csv')
yolov8_df = pd.read_csv(yolov8_metrics_path)
yolov8_df.columns = yolov8_df.columns.str.strip()   # remove any whitespace in column names
last_v8 = yolov8_df.iloc[-1]

yolov8_map50    = float(last_v8['metrics/mAP50(B)'])
yolov8_map5095  = float(last_v8['metrics/mAP50-95(B)'])
yolov8_precision = float(last_v8['metrics/precision(B)'])
yolov8_recall    = float(last_v8['metrics/recall(B)'])

# -----------------------------------------------------------
# STEP 2: Collect metrics from YOLOv5 (from training results object)
# results_v5 was created earlier when you ran model_v5.train(...)
# -----------------------------------------------------------
yolov5_map50    = results_v5.box.map50
yolov5_map5095  = results_v5.box.map
yolov5_precision = results_v5.box.mp    # mean precision
yolov5_recall    = results_v5.box.mr    # mean recall

# -----------------------------------------------------------
# STEP 3: Faster R-CNN — compute average confidence on test set
# Since it was NOT fine-tuned on our dataset, we measure
# average detection confidence as a proxy metric.
# -----------------------------------------------------------
from torchvision import transforms as T
import torch

THRESHOLD = 0.5  # only count confident detections
total_conf_scores = []

model_rcnn.eval()
# Run on up to 50 test images for speed
test_images = list((WORK_DIR / "detection" / "test" / "images").glob("*.png"))[:50]

for img_path in test_images:
    img_pil = Image.open(img_path).convert("RGB")
    img_tensor = T.ToTensor()(img_pil)
    with torch.no_grad():
        pred = model_rcnn([img_tensor])
    scores = pred[0]['scores']
    conf_scores = scores[scores > THRESHOLD]
    if len(conf_scores) > 0:
        total_conf_scores.extend(conf_scores.tolist())

rcnn_avg_conf = np.mean(total_conf_scores) if total_conf_scores else 0.0

# Faster R-CNN has no mAP on our dataset since it was not fine-tuned.
# We set these as 0 / NaN for an honest comparison.
rcnn_map50   = None   # Not applicable — model not trained on our classes
rcnn_map5095 = None
rcnn_precision = None
rcnn_recall    = None

# -----------------------------------------------------------
# STEP 4: Build Summary DataFrame
# -----------------------------------------------------------
comparison_data = {
    "Model": ["YOLOv8n", "YOLOv5n", "Faster R-CNN\n(zero-shot)"],
    "mAP@50":        [round(yolov8_map50,    4), round(yolov5_map50,    4), "N/A (not fine-tuned)"],
    "mAP@50-95":     [round(yolov8_map5095,  4), round(yolov5_map5095,  4), "N/A"],
    "Precision":     [round(yolov8_precision, 4), round(yolov5_precision, 4), "N/A"],
    "Recall":        [round(yolov8_recall,    4), round(yolov5_recall,    4), "N/A"],
    "Avg Conf (>0.5)": ["—", "—", f"{rcnn_avg_conf:.4f}"],
    "Architecture":  ["Anchor-free",  "Anchor-based", "Two-stage (RPN)"],
    "Fine-tuned?":   ["Yes (50 ep.)", "Yes (50 ep.)", "No"],
    "Speed":         ["Real-time ✅", "Real-time ✅", "Slow ❌"],
}

df_compare = pd.DataFrame(comparison_data)
print("=" * 70)
print("        FINAL MODEL COMPARISON TABLE")
print("=" * 70)
print(df_compare.to_string(index=False))
print("=" * 70)

# -----------------------------------------------------------
# STEP 5: Bar Chart — mAP@50 and mAP@50-95 side by side
# -----------------------------------------------------------
models      = ["YOLOv8n", "YOLOv5n"]
map50_vals  = [yolov8_map50,   yolov5_map50]
map95_vals  = [yolov8_map5095, yolov5_map5095]
prec_vals   = [yolov8_precision, yolov5_precision]
recall_vals = [yolov8_recall,    yolov5_recall]

x = np.arange(len(models))
width = 0.2

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("YOLOv8 vs YOLOv5 — Metric Comparison\n(Faster R-CNN excluded: not fine-tuned on helmet dataset)",
             fontsize=13, fontweight='bold')

# ── Left chart: mAP@50 and mAP@50-95 ──
ax1 = axes[0]
bars1 = ax1.bar(x - width/2, map50_vals,  width, label='mAP@50',     color='#1D9E75', edgecolor='white', linewidth=0.5)
bars2 = ax1.bar(x + width/2, map95_vals,  width, label='mAP@50-95',  color='#534AB7', edgecolor='white', linewidth=0.5)

ax1.set_xticks(x)
ax1.set_xticklabels(models, fontsize=11)
ax1.set_ylim(0, 1.05)
ax1.set_ylabel("Score", fontsize=11)
ax1.set_title("mAP Scores", fontsize=12)
ax1.legend(fontsize=10)
ax1.grid(axis='y', alpha=0.3)

# Value labels on bars
for bar in bars1:
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
             f'{bar.get_height():.3f}', ha='center', va='bottom', fontsize=9)
for bar in bars2:
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
             f'{bar.get_height():.3f}', ha='center', va='bottom', fontsize=9)

# ── Right chart: Precision and Recall ──
ax2 = axes[1]
bars3 = ax2.bar(x - width/2, prec_vals,   width, label='Precision', color='#EF9F27', edgecolor='white', linewidth=0.5)
bars4 = ax2.bar(x + width/2, recall_vals, width, label='Recall',    color='#E24B4A', edgecolor='white', linewidth=0.5)

ax2.set_xticks(x)
ax2.set_xticklabels(models, fontsize=11)
ax2.set_ylim(0, 1.05)
ax2.set_ylabel("Score", fontsize=11)
ax2.set_title("Precision & Recall", fontsize=12)
ax2.legend(fontsize=10)
ax2.grid(axis='y', alpha=0.3)

for bar in bars3:
    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
             f'{bar.get_height():.3f}', ha='center', va='bottom', fontsize=9)
for bar in bars4:
    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
             f'{bar.get_height():.3f}', ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.savefig('/content/model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Chart saved to /content/model_comparison.png")

# -----------------------------------------------------------
# STEP 6: Radar / Spider Chart — all 4 qualitative dimensions
# -----------------------------------------------------------
categories   = ['mAP@50', 'mAP@50-95', 'Precision', 'Recall', 'Speed\n(relative)']
N = len(categories)
angles = [n / float(N) * 2 * np.pi for n in range(N)]
angles += angles[:1]   # close the polygon

# Speed: YOLOv8=0.95, YOLOv5=0.90, RCNN=0.20 (normalised 0-1)
v8_vals   = [yolov8_map50, yolov8_map5095, yolov8_precision, yolov8_recall, 0.95]
v5_vals   = [yolov5_map50, yolov5_map5095, yolov5_precision, yolov5_recall, 0.90]
rcnn_vals = [0.0,          0.0,            0.0,              0.0,           0.20]   # no fine-tune

v8_vals   += v8_vals[:1]
v5_vals   += v5_vals[:1]
rcnn_vals += rcnn_vals[:1]

fig2, ax = plt.subplots(figsize=(7, 7), subplot_kw=dict(polar=True))
ax.set_theta_offset(np.pi / 2)
ax.set_theta_direction(-1)
ax.set_xticks(angles[:-1])
ax.set_xticklabels(categories, fontsize=10)
ax.set_ylim(0, 1)
ax.set_yticks([0.2, 0.4, 0.6, 0.8, 1.0])
ax.set_yticklabels(['0.2','0.4','0.6','0.8','1.0'], fontsize=8)
ax.grid(alpha=0.3)

ax.plot(angles, v8_vals,   'o-', linewidth=2,   color='#1D9E75', label='YOLOv8n')
ax.fill(angles, v8_vals,   alpha=0.15,           color='#1D9E75')
ax.plot(angles, v5_vals,   's-', linewidth=2,   color='#534AB7', label='YOLOv5n')
ax.fill(angles, v5_vals,   alpha=0.15,           color='#534AB7')
ax.plot(angles, rcnn_vals, '^-', linewidth=2,   color='#BA7517', label='Faster R-CNN (zero-shot)')
ax.fill(angles, rcnn_vals, alpha=0.10,           color='#BA7517')

ax.set_title("Model Comparison — Radar Chart\n", fontsize=13, fontweight='bold', pad=20)
ax.legend(loc='upper right', bbox_to_anchor=(1.35, 1.15), fontsize=10)

plt.tight_layout()
plt.savefig('/content/radar_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Radar chart saved to /content/radar_comparison.png")

# -----------------------------------------------------------
# STEP 7: Training curve overlay — YOLOv8 vs YOLOv5
# -----------------------------------------------------------
v8_csv_path = Path('/content/runs/detect/train/results.csv')
v5_csv_path = Path('/content/runs/detect/train-3/results.csv')  # YOLOv5 run folder

v8_train = pd.read_csv(v8_csv_path)
v5_train = pd.read_csv(v5_csv_path)
v8_train.columns = v8_train.columns.str.strip()
v5_train.columns = v5_train.columns.str.strip()

fig3, axes3 = plt.subplots(1, 2, figsize=(14, 5))
fig3.suptitle("Training Curves: YOLOv8 vs YOLOv5", fontsize=13, fontweight='bold')

# mAP@50 over epochs
axes3[0].plot(v8_train['metrics/mAP50(B)'],    color='#1D9E75', linewidth=2, label='YOLOv8n')
axes3[0].plot(v5_train['metrics/mAP50(B)'],    color='#534AB7', linewidth=2, label='YOLOv5n', linestyle='--')
axes3[0].set_title("mAP@50 over Epochs")
axes3[0].set_xlabel("Epoch")
axes3[0].set_ylabel("mAP@50")
axes3[0].legend()
axes3[0].grid(alpha=0.3)

# Box loss over epochs
axes3[1].plot(v8_train['train/box_loss'], color='#1D9E75', linewidth=2, label='YOLOv8n')
axes3[1].plot(v5_train['train/box_loss'], color='#534AB7', linewidth=2, label='YOLOv5n', linestyle='--')
axes3[1].set_title("Training Box Loss over Epochs")
axes3[1].set_xlabel("Epoch")
axes3[1].set_ylabel("Box Loss")
axes3[1].legend()
axes3[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('/content/training_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Training curves saved to /content/training_curves.png")

# -----------------------------------------------------------
# STEP 8: Final printed verdict
# -----------------------------------------------------------
print("\n" + "=" * 60)
print("          ✅ FINAL VERDICT")
print("=" * 60)
print(f"""
  YOLOv8n  mAP@50 = {yolov8_map50:.4f}   mAP@50-95 = {yolov8_map5095:.4f}
  YOLOv5n  mAP@50 = {yolov5_map50:.4f}   mAP@50-95 = {yolov5_map5095:.4f}

  ► YOLOv5 shows a slightly higher mAP@50 at 50 epochs because its
    anchor-based design gives an early training boost.

  ► YOLOv8's anchor-free architecture learns more fine-grained
    features and will surpass YOLOv5 with more epochs.

  ► Faster R-CNN (zero-shot) cannot be fairly compared on mAP
    since it was NOT fine-tuned on the helmet dataset.
    For a fair comparison, it would need to be retrained on
    the same data.yaml used by both YOLO models.

  ► Recommended for deployment: YOLOv8n
    (superior architecture, real-time speed, better scalability)
""")
print("=" * 60)